services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop
      PGDATA: /var/lib/postgresql/data/pgdata_shop
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata_shop:/var/lib/postgresql/data/pgdata_shop

  shop:
    image: shop:0.0.1
    container_name: shop_container
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/shop
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "admin"
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500M"
volumes:
  pgdata:
    driver: local
